name = "incendaria"
author = "AIGO Members"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "174ea2109d6fc0abe997f0aef974d62b14f65a6c31d3e27a56656b9a974c7a18"

[versions]
minecraft = "1.19.2"
quilt = "0.23.1"

[options]
datapack-folder = "config/openloader/data"
