name = "incendaria"
author = "AIGO Members"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e74227a3413ef495c0a3001d2e9912ea183da76a4e153d94445b0376e83cc66"

[versions]
minecraft = "1.19.2"
quilt = "0.23.1"

[options]
datapack-folder = "config/openloader/data"
