name = "incendaria"
author = "AIGO Members"
version = "1.8.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4dd41dc0867bb610e6b0d03bc6b662aaa9a462ce8dd6c6c1582c6fb73e0074d3"

[versions]
minecraft = "1.19.2"
quilt = "0.23.1"

[options]
datapack-folder = "config/openloader/data"
