name = "incendaria"
author = "AIGO Members"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e4eef52cc9f4370589e31a452dd325afedebd4bd43bdda76e94f23d0f66db4c8"

[versions]
minecraft = "1.19.2"
quilt = "0.23.1"

[options]
datapack-folder = "config/openloader/data"
