name = "incendaria"
author = "AIGO Members"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a6ca4dbd3be7c15738bfd8231a07c499890d8940d4e776ab3d042451c08539b"

[versions]
minecraft = "1.19.2"
quilt = "0.23.1"
