name = "incendaria"
author = "AIGO Members"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5399e5abbb45a074bdbae11f501d5c851d869d10e206fd273753544467a1394e"

[versions]
minecraft = "1.19.2"
quilt = "0.23.1"
