name = "incendaria"
author = "AIGO Members"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2a56b07d89ab2d919c143b00f5570d9f3589cb5149d03d83b9b2983600e5a179"

[versions]
minecraft = "1.19.2"
quilt = "0.23.1"

[options]
datapack-folder = "config/openloader/data"
