name = "incendaria"
author = "AIGO Members"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b3e20127720b2421c7f0cdbaf6b1e43bc17758e9a14aa13cdb1fad6369e832fe"

[versions]
minecraft = "1.19.2"
quilt = "0.23.1"

[options]
datapack-folder = "config/openloader/data"
