name = "incendaria"
author = "AIGO Members"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a6005bac154d642b64e89ff21d23ec41716ea4a684580bbdaa57aceec2a63c92"

[versions]
minecraft = "1.19.2"
quilt = "0.23.1"
