name = "incendaria"
author = "AIGO Members"
version = "1.8.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "920be4db7131adf13ca5a7b129f89b6cd7a93cae4c840769aa680f45a44bbc2a"

[versions]
minecraft = "1.19.2"
quilt = "0.23.1"

[options]
datapack-folder = "config/openloader/data"
