name = "incendaria"
author = "AIGO Members"
version = "1.8.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e762cbcf6142d2219cde46e354bf0d6a628b48ff9174e2228ccafc67c732a83"

[versions]
minecraft = "1.19.2"
quilt = "0.23.1"

[options]
datapack-folder = "config/openloader/data"
